/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopsIndexRouteImport } from './routes/shops/index'
import { Route as ShopsShopIdRouteImport } from './routes/shops/$shopId'
import { Route as authLoginRouteImport } from './routes/(auth)/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsIndexRoute = ShopsIndexRouteImport.update({
  id: '/shops/',
  path: '/shops/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopsShopIdRoute = ShopsShopIdRouteImport.update({
  id: '/shops/$shopId',
  path: '/shops/$shopId',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/shops': typeof ShopsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/shops': typeof ShopsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/shops/$shopId': typeof ShopsShopIdRoute
  '/shops/': typeof ShopsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/shops/$shopId' | '/shops'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/shops/$shopId' | '/shops'
  id: '__root__' | '/' | '/(auth)/login' | '/shops/$shopId' | '/shops/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  ShopsShopIdRoute: typeof ShopsShopIdRoute
  ShopsIndexRoute: typeof ShopsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/': {
      id: '/shops/'
      path: '/shops'
      fullPath: '/shops'
      preLoaderRoute: typeof ShopsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shops/$shopId': {
      id: '/shops/$shopId'
      path: '/shops/$shopId'
      fullPath: '/shops/$shopId'
      preLoaderRoute: typeof ShopsShopIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  ShopsShopIdRoute: ShopsShopIdRoute,
  ShopsIndexRoute: ShopsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
